spring:
  profiles:
    active: local

server:
  port: 9090
  api:
    listen:
      host: 0.0.0.0
      port: 3002
camel:
  component: jetty

  springboot:
    main-run-controller: true
    name: easy-client-adapter
    stream-caching-enabled: true

easy:
  mambu:
    host: mceasy.sandbox.mambu.com/api
    username: modusboxapi
    password: modusbox123

#informed through runtime variable (java -Doutbound.endpoint=http://localhost:3003)
#outbound:
#  endpoint:  http://localhost:3003