spring:
  profiles:
    active: local

server:
  port: 9091
  api:
    listen:
      host: 0.0.0.0
      port: 3002
camel:
  component: jetty

  springboot:
    main-run-controller: true
    name: easy-core-connector
    stream-caching-enabled: true

### IMPORTANT: the below properties are here for development reference purpose
### for the cluster usage (Helm Chart) it are being set through system variable
### (java -Ddfsp.host=... -Ddfsp.username=... -jar core-connector.jar) into Dockerfile

### properties for DFSP connection
#dfsp:
#  host: https://localhost/api
#  username: user
#  password: pass
#  name: DFSP CO. LTD.

### properties for Mojaloop Connector connection
#ml-conn:
#  outbound:
#    host:  http://localhost:4001